### ISSUE TITLE
Module failure during Gathering Facts - C.ANSIBLE_SSH_CONTROL_PATH is None

### ISSUE THREAD

**Issue by jmacdonagh** [andreasscherbaum/ansible-lxc-ssh#2]
I'm running Ansible 2.3.0.0 on MacOS and running plays against an Ubuntu 16.04 machine which hosts my LXC containers. I add the container via an `add_host` task. Later on when it goes to gather facts the lxc_ssh.py module fails with this traceback:

```
  File "/Users/username/ansible-project/connection_plugins/lxc_ssh.py", line 184, in _build_command
    to_bytes(C.ANSIBLE_SSH_CONTROL_PATH % dict(directory=cpdir)))
TypeError: unsupported operand type(s) for %: 'NoneType' and 'dict'
```

Looks like Ansible's ssh module changed around a bit in ansible/ansible@ac78347f specifically in lib/ansible/constants.py.

**Comment by jmacdonagh** [comment]
Here's a diff that fixes the issue, going off of the commit I linked above. Could certainly be cleaned up.

```diff
--- a/lxc_ssh.py
+++ b/lxc_ssh.py
@@ -18,6 +18,7 @@
 # along with Ansible.  If not, see <http://www.gnu.org/licenses/>.
 #
 import fcntl
+import hashlib
 import os
 import pipes
 import pty
@@ -80,6 +81,16 @@ class Connection(ConnectionBase):
         #self.container = None

     @staticmethod
+    def _create_control_path(host, port, user):
+        '''Make a hash for the controlpath based on con attributes'''
+        pstring = '%s-%s-%s' % (host, port, user)
+        m = hashlib.sha1()
+        m.update(to_bytes(pstring))
+        digest = m.hexdigest()
+        cpath = '%(directory)s/' + digest[:10]
+        return cpath
+
+    @staticmethod
     def _persistence_controls(command):
         '''
         Takes a command array and scans it for ControlPersist and ControlPath
@@ -175,13 +186,20 @@ class Connection(ConnectionBase):
         if controlpersist:
             self._persistent = True
             if not controlpath:
-                cpdir = unfrackpath('$HOME/.ansible/cp')
+                cpdir = unfrackpath(C.ANSIBLE_SSH_CONTROL_PATH_DIR)
                 # The directory must exist and be writable.
                 makedirs_safe(cpdir, 0o700)
                 if not os.access(cpdir, os.W_OK):
                     raise AnsibleError("Cannot write to ControlPath %s" % cpdir)
+                control_path = C.ANSIBLE_SSH_CONTROL_PATH
+                if not control_path:
+                    control_path = self._create_control_path(
+                        self.host,
+                        self._play_context.port,
+                        self._play_context.remote_user
+                    )
                 args = ("-o", "ControlPath={0}".format(
-                    to_bytes(C.ANSIBLE_SSH_CONTROL_PATH % dict(directory=cpdir)))
+                    to_bytes(control_path % dict(directory=cpdir)))
                 )
                 self._add_args("found only ControlPersist; added ControlPath", args)
         ## Finally, we add any caller-supplied extras.
```

**Comment by andreasscherbaum** [comment]
Shouldn't this somehow be combined with an Ansible version check? Else the new code might use the hashing algorithm when running in older Ansible versions ...

**Comment by jmacdonagh** [comment]
It might be good to try this against whichever version of Ansible you use (I'm guessing 2.0?). It seems like it might be backwards compatible but I'm not sure.

**Comment by andreasscherbaum** [comment]
I'm using version 2.2.1.0 and this does not work:

'''
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'module' object has no attribute 'ANSIBLE_SSH_CONTROL_PATH_DIR'
'''

Can you please change this into a PR, and add a version check to it as well?

**Comment by hugoShaka** [comment]
You can version check using `ansible.release.__version__` . If @jmacdonagh don't create the PR I'll do because it's too painful to pin ansible to 2.2.1 on every desktop.

**Comment by dmp1ce** [comment]
I could be wrong but I think this issue should be closed by the commit here: https://github.com/andreasscherbaum/ansible-lxc-ssh/commit/07bb5c98181568bed915f28ca310bad2c199c011

**Comment by andreasscherbaum** [comment]
You might be right there, thanks.
