### ISSUE TITLE
Authentication or permission failure

### ISSUE THREAD

**Issue by TragicWarrior** [andreasscherbaum/ansible-lxc-ssh#26]
All, I am very new to ansible.  I'm not sure if this is an ansible error or an artifact of the lxc-ssh plugin.  I have lxc 3.0.3 running on a server.  On my laptop I have ansible 2.5.1 installed.  I have ssh key authentication setup between my laptop and the server.  My configuration files look like this:

/etc/ansible/hosts

```
[centos6-servers]                                                               
container1 ansible_host=stellarvelocity.com ansible_user=root ansible_connection=lxc_ssh ansible_ssh_extra_args=centos6-64-consolecraze
```

/etc/ansible/ansible.cfg

```
[defaults]                                                                    
connection_plugins = /usr/share/ansible/plugins
```

When I try to run the following command:

```
ansible container1 -m ping
```

I get the following error:

```
container1 | UNREACHABLE! => {
    "changed": false, 
    "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo /tmp/ansible-tmp-1576882883.93-65515531639136 `\" && echo ansible-tmp-1576882883.93-65515531639136=\"` echo /tmp/ansible-tmp-1576882883.93-65515531639136 `\" ), exited with result 1, stdout output: Error: not found\r\n", 
    "unreachable": true
}
```

Scouring places like StackOverflow, I have repeatedly found the suggestion to change the ```remote_tmp``` param in ansible.cfg to something like ```/tmp``` which I tried but did not fix the issue.

Is this a plug-in issue, ansible issue, or newbie issue?

**Comment by andreasscherbaum** [comment]
Error: not found

Does /tmp exist? Which permissions does it have?

**Comment by TragicWarrior** [comment]
Yes.  ```/tmp``` exits on the remote system (where lxc is running).  The umask is 1777.

**Comment by TragicWarrior** [comment]
@andreasscherbaum , I'm not a python guy but could this be the issue:

https://github.com/ansible/ansible/issues/41060

?

**Comment by TragicWarrior** [comment]
@andreasscherbaum , I copied my hosts and configuration over to a Centos 8 system running ansbile 2.8.5 and am still getting the same error.

**Comment by andreasscherbaum** [comment]
That #41060 looks like a different problem. In your case the error is "Error: not found".

Can you run that with a couple more -v options, and see if that yields anything useful?

**Comment by TragicWarrior** [comment]
With verbosity level 3

```
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Oct  7 2019, 17:58:22) [GCC 8.2.1 20180905 (Red Hat 8.2.1-3)]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin
META: ran handlers
XXX connect
<stellarvelocity.com> ESTABLISH SSH CONNECTION FOR USER: root
<stellarvelocity.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=publickey,gssapi-with-mic,gssapi-keyex,hostbased -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/9fc1c715ec -tt stellarvelocity.com 'which lxc'
<stellarvelocity.com> (0, b'/usr/bin/lxc\r\n', b'Shared connection to stellarvelocity.com closed.\r\n')
XXX connect
<stellarvelocity.com> ESTABLISH SSH CONNECTION FOR USER: root
<stellarvelocity.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=publickey,gssapi-with-mic,gssapi-keyex,hostbased -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/9fc1c715ec -tt stellarvelocity.com 'which lxc-info'
<stellarvelocity.com> (0, b'/usr/bin/lxc-info\r\n', b'Shared connection to stellarvelocity.com closed.\r\n')
LXC v2
XXX exec_command: /bin/sh -c '( umask 77 && mkdir -p "` echo /tmp/ansible-tmp-1576885842.1881857-217844459020820 `" && echo ansible-tmp-1576885842.1881857-217844459020820="` echo /tmp/ansible-tmp-1576885842.1881857-217844459020820 `" ) && sleep 0'
XXX connect
<stellarvelocity.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=publickey,gssapi-with-mic,gssapi-keyex,hostbased -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/9fc1c715ec -tt stellarvelocity.com 'lxc exec centos6-64-consolecraze --mode=non-interactive -- /bin/sh -c '"'"'/bin/sh -c '"'"'"'"'"'"'"'"'( umask 77 && mkdir -p "` echo /tmp/ansible-tmp-1576885842.1881857-217844459020820 `" && echo ansible-tmp-1576885842.1881857-217844459020820="` echo /tmp/ansible-tmp-1576885842.1881857-217844459020820 `" ) && sleep 0'"'"'"'"'"'"'"'"''"'"''
<stellarvelocity.com> (1, b'Error: not found\r\n', b'Shared connection to stellarvelocity.com closed.\r\n')
XXX close
container1 | UNREACHABLE! => {
    "changed": false,
    "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo /tmp/ansible-tmp-1576885842.1881857-217844459020820 `\" && echo ansible-tmp-1576885842.1881857-217844459020820=\"` echo /tmp/ansible-tmp-1576885842.1881857-217844459020820 `\" ), exited with result 1, stdout output: Error: not found\r\n",
    "unreachable": true
}
```

**Comment by andreasscherbaum** [comment]
First of all, see if you can enable pipelineing. That should speed up things.

Second, what happens if you run this as root on the host:
```
lxc exec centos6-64-consolecraze --mode=non-interactive -- hostname
lxc exec centos6-64-consolecraze --mode=non-interactive -- ls -ld /tmp
```

**Comment by TragicWarrior** [comment]
```
root@ironkite:~# lxc exec centos6-64-consolecraze --mode=non-interactive -- hostname
Error: not found
```

**Comment by andreasscherbaum** [comment]
Well, there is your answer. What exactly is not there? The "centos6-64-consolecraze" VM?

**Comment by TragicWarrior** [comment]
```
root@ironkite:~# lxc-ls --fancy |grep cons
centos6-64-consolecraze      RUNNING 1         -      172.16.0.131            -    false
```

**Comment by TragicWarrior** [comment]
It's definitely there and running.

**Comment by TragicWarrior** [comment]
On my system there is a binary "lxc-execute"  is that what should be invoked (vs lxc exec)?

**Comment by andreasscherbaum** [comment]
So, wait, you have a "lxc" and "lxc-execute"? Or no "lxc"?

https://github.com/andreasscherbaum/ansible-lxc-ssh/blob/master/lxc_ssh.py#L135

**Comment by TragicWarrior** [comment]
I have lxc and lxc-execute

**Comment by TragicWarrior** [comment]
man lxc-execute

```
lxc-execute(1)                                                                                    lxc-execute(1)

NAME
       lxc-execute - run an application inside a container.
```

**Comment by TragicWarrior** [comment]
I think this is the desired behavior (correct me if I'm wrong)

```
root@ironkite:~# lxc-attach -n centos6-64-consolecraze -- hostname
centos6-64-consolecraze
```

**Comment by andreasscherbaum** [comment]
Looks like LXC v3 wants to screw around, keep the "lxc" but move everything else into separate binaries. Now I don't have a v3 around (yet), and can't test it.

If you want, you can submit a PR which can clearly identify between v1, v2 und v3. And then use the correct binary everytime "lxc_version" is used in the module.

**Comment by TragicWarrior** [comment]
Sadly, I don't know python.  If things were written in C or PHP I would be glad to do so.

**Comment by andreasscherbaum** [comment]
Then unfortunately this has to wait until I have access to LXC v3 (or someone else submits the patch). Sorry.

**Comment by TragicWarrior** [comment]
@andreasscherbaum , LXC 3 is part of Ubuntu 18.04.3 LTS.  I'll pay $150 USD to for this to work :)

**Comment by andreasscherbaum** [comment]
Not in my Ubuntu here:

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```

```
which lxc
/usr/bin/lxc
```

```
which lxc-execute
```

```
apt-cache search lxc-execute
```

Which OS/Version are you using there as host?

**Comment by TragicWarrior** [comment]
```
root@ironkite:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

**Comment by andreasscherbaum** [comment]
What about the lxc-execute? Where is that, and which package includes it?

**Comment by TragicWarrior** [comment]
```
root@ironkite:~# which lxc-execute
/usr/bin/lxc-execute
```

```
root@ironkite:~# apt-cache search lxc-execute
```

^^^ produces nada

**Comment by andreasscherbaum** [comment]
Uhm, that is strange.

```
dpks -S /usr/bin/lxc-execute
```
?

**Comment by TragicWarrior** [comment]
```
root@ironkite:/usr/bin# dpkg -S /usr/bin/lxc-execute
lxc-utils: /usr/bin/lxc-execute
```

**Comment by andreasscherbaum** [comment]
I don't have "lxc-utils" installed, but I can still use "lxc" perfectly fine to run commands:

```
root@<host> ~ # lxc exec <container> --mode=non-interactive -- hostname
<container>
```

This is curious. In your debug output, lxc_ssh.py clearly identified this as "v2", and therefore will use "lxc exec". What happens if you just start a shell in the container?

```
lxc exec centos6-64-consolecraze --mode=non-interactive -- /bin/sh
```

Also can you try another OS for the virtual machine, and see if the problem persists? CentOS 6 is quite old ...

**Comment by TragicWarrior** [comment]
```
root@ironkite:~# lxc exec centos7-hisgrip --mode=non-interactive -- /bin/sh
Error: not found
```

**Comment by TragicWarrior** [comment]
The machine was originally Ubuntu 16.04.X LTS and was upgraded in place to 18.04 (via do-release-upgrade) so maybe some artifacts of that?  It _was_ LXC version to 2 and I remember having to run ```lxc-update-config``` afterward to fix-up the v3 config changes.

**Comment by andreasscherbaum** [comment]
At this point: I think lxc_ssh.py is picking the correct binaries and commands, but something is wrong with your VM. You can't even start a shell in it, how can Ansible do any configuration?

Please try another OS for the VM, and see if that error persists (should be easy to spin up another VM). When you can start a shell again, I think the Ansible plugin will start working as well.

**Comment by TragicWarrior** [comment]
Well, I can't just use another host.  That is a production server that cannot be taken offline.  What about using lxc-attach.  It clearly works:

```
root@ironkite:~# lxc-attach -n centos7-hisgrip -- /bin/sh
sh-4.2# exit
```

**Comment by andreasscherbaum** [comment]
lxc-attach is LXC v1 in this module:
https://github.com/andreasscherbaum/ansible-lxc-ssh/blob/master/lxc_ssh.py#L720

Also I don't see why "lxc exec" is not working just on your host.

I just installed "lxc-utils" on one Ubuntu 18 host:

```
lxc-execute -n <container> -- pwd
lxc-execute: <container>: tools/lxc_execute.c: main: 200 Executing a container with no configuration file may crash the host
```

Looks like you are also spinning up the containers in a different way. Not sure what else is different ...

**Comment by TragicWarrior** [comment]
My containers are spun up automatically ( lxc.start.auto = 1 ).  Like I said, I don't really know python but I'm curios as to where self.lcx_version get set from?

**Comment by andreasscherbaum** [comment]
I mean how the containers are created. I'm starting mine using the "lxd_container" module. And I can't use "lxc-attach":

```
lxc-attach: <container>: attach.c: lxc_attach: 1095 Failed to get init pid
```

Switching to "lxc-attach" from "lxc exec" is therefore not an option. Plus this will confuse the v1 commands as well ...

**Comment by TragicWarrior** [comment]
When I need to start a container that's not already running I do:

```
lxc-start -d -n centos6-64-consolecraze
```

**Comment by TragicWarrior** [comment]
My containers are created by doing something like:

lxc-create -n <name> -t download

**Comment by andreasscherbaum** [comment]
You have a config file for the container somewhere?

Anyway, I don't know what else is different in your setup, and apparently I can't re-create such an environment here. Looks like I ran out of my options.

**Comment by TragicWarrior** [comment]
```
root@ironkite:/var/lib/lxc/centos6-64-consolecraze# cat config
lxc.mount.auto = proc:mixed sys:ro
lxc.tty.max = 4
lxc.pty.max = 1024
lxc.tty.dir = lxc
lxc.arch = x86_64
lxc.seccomp.profile = /usr/share/lxc/config/common.seccomp
lxc.cgroup.devices.deny = a
lxc.cgroup.devices.allow = c *:* m
lxc.cgroup.devices.allow = b *:* m
lxc.cgroup.devices.allow = c 1:3 rwm
lxc.cgroup.devices.allow = c 1:5 rwm
lxc.cgroup.devices.allow = c 1:7 rwm
lxc.cgroup.devices.allow = c 5:0 rwm
lxc.cgroup.devices.allow = c 1:8 rwm
lxc.cgroup.devices.allow = c 1:9 rwm
lxc.cgroup.devices.allow = c 136:* rwm
lxc.cgroup.devices.allow = c 5:2 rwm
lxc.uts.name = centos6-64-consolecraze
lxc.net.0.type = veth
lxc.net.0.flags = up
lxc.net.0.link = lxcbr0
lxc.net.0.hwaddr = 00:16:3e:10:3c:ec
lxc.cap.drop = mac_admin
lxc.cap.drop = mac_override
lxc.cap.drop = setfcap
lxc.cap.drop = sys_module
lxc.cap.drop = sys_nice
lxc.cap.drop = sys_pacct
lxc.cap.drop = sys_rawio
lxc.cap.drop = sys_time
lxc.hook.clone = /usr/share/lxc/hooks/clonehostname
lxc.rootfs.path = /var/lib/lxc/centos6-64-consolecraze/rootfs
lxc.start.auto = 1
```

**Comment by andreasscherbaum** [comment]
I'm beginning to suspect that this is a problem caused by you using "lxc" instead of "lxd", but I can't verify the details. Although the module is named "lxc_ssh", the name was given by the original author and I simply forked it and continued maintenance.

In my case, I'm using LXD everywhere. To create and spin up VMs, destroy them, configuration, ect.
LXD is using LXC under the hood, but I don't know how much difference it makes if you use LXC directly.

**Comment by TragicWarrior** [comment]
Oh.  I absolutely _do not_ use LXD--only LXC.  I have no desire to use LXD.  I need a solution for LXC.

**Comment by TragicWarrior** [comment]
@andreasscherbaum , I did see the original project which seems unmaintained.  I get that you cannot break compatibility, but would it be possible for you to at least create a branch that always uses lxc-attach instead of lxc just so I can test if that does the job?

**Comment by andreasscherbaum** [comment]
It's not just replacing "lxc exec" with "lxc-attach". The version detection needs to be updated, and needs to include a check if the container was created by "lxc" or "lxd". All "lxc" commands (there are more, like copy and such) need to be updated ect. And it also needs some basic testing (not to talk about the CI which I haven't found time to setup).
