### ISSUE TITLE
using sudo to run lxc-attach

### ISSUE THREAD

**Issue by manelclos** [andreasscherbaum/ansible-lxc-ssh#3]
Hi, I tried to fix this in a number of ways, but ended up adding "sudo" in front of every "lxc-attach" command in the plugin.

I really need to login as non-root as root login is disabled, and that trick makes it work.

It would be nice to maybe have that "sudo" as an option, or use the same "become" method...

**Comment by andreasscherbaum** [comment]
I remember that I had some trouble when using non-root accounts, unfortunately. But can't remember exactly.

If this works for you, can you provide this as a PR, along with a config option for the become method?

**Comment by trygvis** [comment]
Just adding sudo works for me to. Don't know enough ansible to help out with patching yes :(

**Comment by xMAC94x** [comment]
I have the same problem, if the version suppors python3 #5 i could try to add something like a confuration that will execute a sudo before attach

**Comment by andreasscherbaum** [comment]
I think it's more complicated than just adding "sudo". You need to use whatever mechanism Ansible itself is using to gain root access, that might not be "sudo".
