### ISSUE TITLE
Error if lxc_host is numeric

### ISSUE THREAD

**Issue by vegaelle** [andreasscherbaum/ansible-lxc-ssh#43]
I’m using this plugin with a proxmox server, which uses numbers as names for the containers. I upgraded the plugin for some reason, and it stopped working (i was using `ansible_ssh_extra_args` as container names in my inventory), with an exception saying that `int` objects don’t have a `read` method.

I fixed locally this problem by casting the call to `self.get_option('lxc_host')` to string, but it probably should be fixed in upstream.

**Comment by andreasscherbaum** [comment]
We just merged a number of changes into this plugin. However I'm not sure any of those will fix your issues.

What exactly is your error message, what hostname are you using? It does not look like an IP?

**Comment by andreasscherbaum** [comment]
@vegaelle Is this ticket still relevant?

**Comment by zedar187** [comment]
I recently switched from the upstream version to this fork . Had the same error as mentioned above, because the hosts file still had `ansible_ssh_extra_args=` instead of `lxc_container`. Everything is running fine again since changing the entries.

**Comment by andreasscherbaum** [comment]
@zedar187 To clarify: running the current version from this repository fixes your problem, and everything runs fine?

**Comment by zedar187** [comment]
@andreasscherbaum yes, the plugins works in the current version. Running on a debian bullseye node with its according python version.

chifflier's version needs the parameter `ansible_ssh_extra_args=container`, whereas your fork depends on `lxc_container=container`. My hosts file still had `ansible_ssh_extra_args=103`, which resulted in the same error as @vegaelle mentioned ("int objects don’t have a read method"). Just needed to edit the hosts file to `lxc_container=103`.

**Comment by andreasscherbaum** [comment]
Close this issue as @zedar187 confirms that one of the recent updates solve this problem.
