### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by hugoShaka** [andreasscherbaum/ansible-lxc-ssh#5]
I'd like to add python3 support for this plugin (not a big deal, only 2 or 3 lines to correct) but shall I edit the plugin to test the python version or create another branch ?

**Comment by andreasscherbaum** [comment]
Can you send a PR, which works with both Python 2 and 3? I will review and merge it.

**Comment by xMAC94x** [comment]
@andreasscherbaum have you had a look at the https://github.com/TuxCoder/ansible-lxc-ssh/tree/python3-fix branch ?
i am no python expert but i think it should be possible with a http://sweetme.at/2013/10/21/how-to-detect-python-2-vs-3-in-your-python-script version.
I can try to to prepare a PR if you want so?

**Comment by andreasscherbaum** [comment]
That seems easy enough to you can add the 2/3 check, and include support for both versions.

Please provide a PR which I can merge. Thank you!

**Comment by andreasscherbaum** [comment]
@xMAC94x Since this was brought up again, did you find time to make this patch working with Python 2 and 3?
