### ISSUE TITLE
"Failed to connect to the host via ssh: Permission denied (publickey,password).\r\n"

### ISSUE THREAD

**Issue by alex9434** [andreasscherbaum/ansible-lxc-ssh#8]
I cannot get the plugin to work. I have ansible installed inside a LXC container and want to use it to manage  other containers. I have the following line in my hosts:

gigabyte ansible_connection=lxc_ssh ansible_ssh_extra_args=magento

(Gigabyte is the name of the host, it is reachable from within the LXC container with ssh gigabyte). However, where do I put username and password for the ssh to the host? I have tried the following line:

[all:vars]
ansible_user=lxcuser
ansible_pass=**** (removed)

What am I doing wrong? Please help!

**Comment by andreasscherbaum** [comment]
Have to admit that I never used the plugin with username and password, always with public keys.
